#!/usr/bin/env node

var output = '';

var results = {
    score: null,
    passed: null,
    failed: null,
    error: null
};

process.stdin.on('data', function(data) {
    output += data;
});

process.stdin.on('end', function() {
    gradeAssessment(output);
    process.stdout.write(JSON.stringify(results, null, 4));
});

function gradeAssessment(data) {
    if (data.match(/mocha/)) var testType = 'mocha';
    else if (data.match(/testem/)) var testType = 'testem';
    else return results.error = 'Error occured while grading assessment';
    results.passed = getNumberOfTests(data, 'pass', testType);
    results.failed = getNumberOfTests(data, 'fail', testType);
    if (!results.passed && !results.failed) results.error = 'Error occurred while grading assessment';
    results.score = results.passed / (results.passed + results.failed) * 100;
}

function getNumberOfTests(data, status, type) {
    var testDictionary = {
        mocha: '(\\d+)\\s+' + status + 'ing',
        testem: '#\\s+' + status + '\\s+(\\d+)'
    };
    var matchArr = data.match(testDictionary[type]);
    return matchArr ? Number(matchArr[1]) : 0;
}

